alter table public.download_portal_users
  add column if not exists is_admin boolean not null default false;

alter table public.download_portal_devices
  add column if not exists telemetry_token_hash text;

update public.download_portal_users
set is_admin = true,
    updated_at = now()
where user_id in (
  select id from auth.users where lower(email) = lower('552078638@qq.com')
);

create table if not exists public.listing_usage_sessions (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  device_id text not null,
  app_version text not null default '',
  started_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now(),
  constraint listing_usage_sessions_device_id_length
    check (char_length(device_id) between 32 and 128)
);

create index if not exists listing_usage_sessions_user_last_seen_idx
  on public.listing_usage_sessions (user_id, last_seen_at desc);
create index if not exists listing_usage_sessions_device_last_seen_idx
  on public.listing_usage_sessions (device_id, last_seen_at desc);

create table if not exists public.listing_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_id uuid not null references public.listing_usage_sessions(id) on delete cascade,
  device_id text not null,
  event_type text not null,
  outcome text not null,
  app_version text not null default '',
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint listing_usage_events_type
    check (event_type in ('listing_prepare','listing_execute','batch_prepare','batch_execute')),
  constraint listing_usage_events_outcome
    check (outcome in ('started','completed','failed'))
);

create index if not exists listing_usage_events_user_time_idx
  on public.listing_usage_events (user_id, occurred_at desc);
create index if not exists listing_usage_events_session_time_idx
  on public.listing_usage_events (session_id, occurred_at desc);

alter table public.listing_usage_sessions enable row level security;
alter table public.listing_usage_events enable row level security;

revoke all on table public.listing_usage_sessions from anon, authenticated;
revoke all on table public.listing_usage_events from anon, authenticated;
grant all on table public.listing_usage_sessions to service_role;
grant all on table public.listing_usage_events to service_role;
grant usage, select on sequence public.listing_usage_events_id_seq to service_role;

create or replace function public.get_listing_usage_admin_snapshot()
returns jsonb
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  caller uuid := auth.uid();
  payload jsonb;
begin
  if caller is null or not exists (
    select 1
    from public.download_portal_users
    where user_id = caller and is_admin = true
  ) then
    raise exception 'not_authorized' using errcode = '42501';
  end if;

  with session_stats as (
    select
      user_id,
      count(*)::bigint as launch_count,
      min(started_at) as first_used_at,
      max(last_seen_at) as session_last_seen_at
    from public.listing_usage_sessions
    group by user_id
  ),
  event_stats as (
    select
      user_id,
      count(*) filter (where event_type='listing_prepare' and outcome='started')::bigint as listing_prepare_started,
      count(*) filter (where event_type='listing_prepare' and outcome='completed')::bigint as listing_prepare_completed,
      count(*) filter (where event_type='listing_prepare' and outcome='failed')::bigint as listing_prepare_failed,
      count(*) filter (where event_type='listing_execute' and outcome='started')::bigint as listing_execute_started,
      count(*) filter (where event_type='listing_execute' and outcome='completed')::bigint as listing_execute_completed,
      count(*) filter (where event_type='listing_execute' and outcome='failed')::bigint as listing_execute_failed,
      count(*) filter (where event_type='batch_prepare' and outcome='started')::bigint as batch_prepare_started,
      count(*) filter (where event_type='batch_prepare' and outcome='completed')::bigint as batch_prepare_completed,
      count(*) filter (where event_type='batch_prepare' and outcome='failed')::bigint as batch_prepare_failed,
      count(*) filter (where event_type='batch_execute' and outcome='started')::bigint as batch_execute_started,
      count(*) filter (where event_type='batch_execute' and outcome='completed')::bigint as batch_execute_completed,
      count(*) filter (where event_type='batch_execute' and outcome='failed')::bigint as batch_execute_failed
    from public.listing_usage_events
    group by user_id
  ),
  device_stats as (
    select
      user_id,
      count(*) filter (where enabled=true and revoked_at is null)::bigint as active_devices,
      max(last_seen_at) as device_last_seen_at
    from public.download_portal_devices
    group by user_id
  ),
  rows as (
    select
      p.user_id,
      u.email,
      coalesce(nullif(p.display_name,''), u.email, '') as display_name,
      p.enabled,
      p.expires_at,
      p.max_devices,
      coalesce(ds.active_devices,0) as active_devices,
      coalesce(ss.launch_count,0) as launch_count,
      ss.first_used_at,
      greatest(ss.session_last_seen_at, ds.device_last_seen_at) as last_seen_at,
      exists (
        select 1
        from public.listing_usage_sessions live
        where live.user_id = p.user_id
          and live.last_seen_at >= now() - interval '150 seconds'
          and (live.ended_at is null or live.ended_at >= now() - interval '150 seconds')
      ) as online,
      coalesce(es.listing_prepare_started,0) as listing_prepare_started,
      coalesce(es.listing_prepare_completed,0) as listing_prepare_completed,
      coalesce(es.listing_prepare_failed,0) as listing_prepare_failed,
      coalesce(es.listing_execute_started,0) as listing_execute_started,
      coalesce(es.listing_execute_completed,0) as listing_execute_completed,
      coalesce(es.listing_execute_failed,0) as listing_execute_failed,
      coalesce(es.batch_prepare_started,0) as batch_prepare_started,
      coalesce(es.batch_prepare_completed,0) as batch_prepare_completed,
      coalesce(es.batch_prepare_failed,0) as batch_prepare_failed,
      coalesce(es.batch_execute_started,0) as batch_execute_started,
      coalesce(es.batch_execute_completed,0) as batch_execute_completed,
      coalesce(es.batch_execute_failed,0) as batch_execute_failed,
      (
        select s.app_version
        from public.listing_usage_sessions s
        where s.user_id = p.user_id and s.app_version <> ''
        order by s.last_seen_at desc
        limit 1
      ) as latest_app_version
    from public.download_portal_users p
    join auth.users u on u.id = p.user_id
    left join session_stats ss on ss.user_id = p.user_id
    left join event_stats es on es.user_id = p.user_id
    left join device_stats ds on ds.user_id = p.user_id
  )
  select jsonb_build_object(
    'generated_at', now(),
    'online_window_seconds', 150,
    'users', coalesce(
      jsonb_agg(
        jsonb_build_object(
          'user_id', user_id,
          'email', email,
          'display_name', display_name,
          'enabled', enabled,
          'expires_at', expires_at,
          'online', online,
          'first_used_at', first_used_at,
          'last_seen_at', last_seen_at,
          'launch_count', launch_count,
          'listing_prepare_started', listing_prepare_started,
          'listing_prepare_completed', listing_prepare_completed,
          'listing_prepare_failed', listing_prepare_failed,
          'listing_execute_started', listing_execute_started,
          'listing_execute_completed', listing_execute_completed,
          'listing_execute_failed', listing_execute_failed,
          'batch_prepare_started', batch_prepare_started,
          'batch_prepare_completed', batch_prepare_completed,
          'batch_prepare_failed', batch_prepare_failed,
          'batch_execute_started', batch_execute_started,
          'batch_execute_completed', batch_execute_completed,
          'batch_execute_failed', batch_execute_failed,
          'active_devices', active_devices,
          'max_devices', max_devices,
          'latest_app_version', coalesce(latest_app_version,'')
        )
        order by online desc, last_seen_at desc nulls last, email
      ),
      '[]'::jsonb
    )
  ) into payload
  from rows;

  return payload;
end;
$$;

revoke all on function public.get_listing_usage_admin_snapshot() from public, anon;
grant execute on function public.get_listing_usage_admin_snapshot() to authenticated;
